In [1]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")
pay = float(hrs) * float(rate)
print("Pay:", pay)

Enter Hours:35
Enter Rate:2.75
Pay: 96.25


In [1]:
x = 0
if x < 2 :
    print('Small')
elif x < 10 :
    print('Medium')
else :
    print('LARGE')
print('All done')

Small
All done


exersise 3.2


In [2]:
hrs = input("Enter Hours:")
h = float(hrs)
rate = input("Enter the Rate:")
r = float(rate)
if h <= 40:
    print( h  * r)
elif h > 40:
    print(40* r + (h-40)*1.5*r)

Enter Hours:45
Enter the Rate:10.50
498.75


3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85. 

In [ ]:

score = input("Enter Score: ")
s =  float(score)
x = 'Error'
if s >= 0.9:
    x = 'A'
elif s >=0.8:
    x='B'
elif s >=0.7:
    x='C'
elif s >= 0.6:
    x='D'
elif s < .6:
    x ='F'
else:
    x ="Out of Range"
print (x)

In [1]:
def thing():
    print('Hello')

print('There')

There


In [2]:
def func(x) :
    print(x)

func(10)
func(20)

10
20


In [5]:
def stuff():
    print('Hello')
    return
    print('World')

stuff()

Hello


In [6]:
def greet(lang):
    if lang == 'es':
        return 'Hola'
    elif lang == 'fr':
        return 'Bonjour'
    else:
        return 'Hello'

print(greet('fr'),'Michael')

Bonjour Michael


In [7]:
def addtwo(a, b):
    added = a + b
    return a

x = addtwo(2, 7)
print(x)

2


4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function. 

In [8]:
def computepay(h, r):
    return 42.37

hrs = input("Enter Hours:")
p = computepay(10, 20)
print("Pay", p)

Enter Hours:10
Pay 42.37


In [10]:
def computepay(h,r):
    if h > 40:
        p = 1.5 * r * (h - 40) + (40 *r)
    else:
        p = h * r
    return p
    
hrs = input("Enter Hours:")
hr = float(hrs)
rphrs = input("Enter rate per hour:")
rphr = float(rphrs)

p = computepay(hr,rphr)
print("Pay",p)

Enter Hours:45
Enter rate per hour:10.50
Pay 498.75


In [1]:
smallest_so_far = -1
for the_num in [9, 41, 12, 3, 74, 15] :
   if the_num < smallest_so_far :
      smallest_so_far = the_num
print(smallest_so_far)

-1


In [2]:
tot = 0 
for i in [5, 4, 3, 2, 1] :
    tot = tot + 1
print(tot)

5


In [10]:
num = 0
largest = -1
smallest = None
while True:
    num = input("Enter a number: ")
    if num == "done" :
        break
    try :
        numb = int(num)
    except :
        print('Invalid input')
    if smallest is None :
        smallest = numb
    elif numb < smallest :
        smallest = numb
    elif numb > largest :
        largest = numb
print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 10
Enter a number: 7
Enter a number: 2
Enter a number: 4
Enter a number: bob
Invalid input
Enter a number: done
Maximum is 4
Minimum is 2


In [26]:
largest = None
smallest = None

while True:
    num = input("Enter a Number: ")

    if num == 'done':
        break
try:
    num = int(num)
except:
    print("Invalid input")
    
    continue
    
    if smallest is None:
        smallest = num
    elif num < smallest: 
        smallest = num
    if largest is None:
        largest = num
    elif num > largest:
        largest = num
    
    #print("Invalid input")
print("Maximum is", largest)
print("Minimum is", smallest)


Enter a Number: 7
Enter a Number: 2
Enter a Number: 4
Enter a Number: 10
Enter a Number: bob
Enter a Number: done


SyntaxError: 'continue' not properly in loop (<ipython-input-26-f54677a6bede>, line 14)

In [19]:
largest = None
smallest = None
while True:
    try:
        num = input("Enter a number: ")
        if num == "done":
            break
        #print (num)
        num = int(num)
        if largest is None or largest < num:
            largest = num
        elif smallest is None or smallest > num:
             smallest =num
    except:
        print("Invalid input")
print ("Maximum is", largest)
print ("Minimum is", smallest)

Enter a number: 7
Enter a number: 2
Enter a number: 4
Enter a number: 10
Enter a number: bob
Invalid input
Enter a number: done
Maximum is 10
Minimum is 2


In [4]:
# Program to multiply two matrices using list comprehension
 
# take a 3x3 matrix
A = [[1, 0, 0],
    [1/3, 1/3, 1/3],
    [0, 1, 0]]
 
# take a 3x4 matrix
B = [[1, 0, 0],
    [1/3, 1/3, 1/3],
    [0, 1, 0]]
 
# result will be 3x4
result = [[sum(a * b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]
 
for r in result:
    print(r)

[1.0, 0.0, 0.0]
[0.4444444444444444, 0.4444444444444444, 0.1111111111111111]
[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]


In [18]:
import numpy as np
# take a 3x3 matrix
A = [[1, 0, 0],
    [1/3, 1/3, 1/3],
    [0, 1, 0]]
 
B=[[1, 0, 0],
    [1/3, 1/3, 1/3],
    [0, 1, 0]]
 
# result will be 3x4
 
result= [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
result = np.dot (A,A)
 
for r in result:
    print(r)

[1. 0. 0.]
[0.44444444 0.44444444 0.11111111]
[0.33333333 0.33333333 0.33333333]


In [25]:
import numpy as np

matrix = np.array([[1, 0, 0],[1/3, 1/3, 1/3],[0, 1, 0]])

power = np.linalg.matrix_power(matrix,4)

print(power)


[[1.         0.         0.        ]
 [0.67901235 0.2345679  0.08641975]
 [0.59259259 0.25925926 0.14814815]]
